-- =========================
-- 权限域
-- =========================
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    mobile VARCHAR(32) NULL,
    email VARCHAR(128) NULL,
    org_name VARCHAR(128) NULL,
    role_scope VARCHAR(128) NULL,
    region_code VARCHAR(32) NULL,
    account_status TINYINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_user_username (username),
    KEY idx_sys_user_mobile (mobile),
    KEY idx_sys_user_org_name (org_name),
    KEY idx_sys_user_region_code (region_code),
    KEY idx_sys_user_account_status (account_status),
    KEY idx_sys_user_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT NOT NULL,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(64) NOT NULL,
    data_scope VARCHAR(64) NULL,
    subsystem_scope VARCHAR(255) NULL,
    menu_scope VARCHAR(1000) NULL,
    sort_no INT NULL,
    role_status TINYINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_role_role_code (role_code),
    KEY idx_sys_role_role_status (role_status),
    KEY idx_sys_role_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_user_role_user_role (user_id, role_id),
    KEY idx_sys_user_role_role_id (role_id),
    KEY idx_sys_user_role_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_role_menu (
    id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    menu_code VARCHAR(64) NOT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_role_menu_role_menu (role_id, menu_code),
    KEY idx_sys_role_menu_menu_code (menu_code),
    KEY idx_sys_role_menu_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =========================
-- 资产域
-- =========================
CREATE TABLE IF NOT EXISTS asset_network (
    id BIGINT NOT NULL,
    network_code VARCHAR(64) NOT NULL,
    network_name VARCHAR(128) NOT NULL,
    network_type VARCHAR(32) NULL,
    region_code VARCHAR(32) NULL,
    owner_unit VARCHAR(128) NULL,
    operation_unit VARCHAR(128) NULL,
    service_status TINYINT NOT NULL DEFAULT 1,
    health_level TINYINT NULL,
    risk_level TINYINT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_asset_network_code (network_code),
    KEY idx_asset_network_type (network_type),
    KEY idx_asset_network_region (region_code),
    KEY idx_asset_network_status (service_status),
    KEY idx_asset_network_health (health_level),
    KEY idx_asset_network_risk (risk_level),
    KEY idx_asset_network_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS asset_pipe_section (
    id BIGINT NOT NULL,
    section_code VARCHAR(64) NOT NULL,
    network_id BIGINT NOT NULL,
    section_name VARCHAR(128) NULL,
    pipe_material VARCHAR(64) NULL,
    diameter_mm DECIMAL(10,2) NULL,
    bury_depth_m DECIMAL(10,2) NULL,
    pipe_age_year INT NULL,
    old_flag TINYINT NULL,
    renovation_status TINYINT NULL,
    start_node_id BIGINT NULL,
    end_node_id BIGINT NULL,
    latest_health_score DECIMAL(8,2) NULL,
    latest_risk_level TINYINT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_asset_pipe_section_code (section_code),
    KEY idx_asset_pipe_section_network_id (network_id),
    KEY idx_asset_pipe_section_name (section_name),
    KEY idx_asset_pipe_section_material (pipe_material),
    KEY idx_asset_pipe_section_diameter (diameter_mm),
    KEY idx_asset_pipe_section_age (pipe_age_year),
    KEY idx_asset_pipe_section_renovation (renovation_status),
    KEY idx_asset_pipe_section_health (latest_health_score),
    KEY idx_asset_pipe_section_risk (latest_risk_level),
    KEY idx_asset_pipe_section_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS asset_node (
    id BIGINT NOT NULL,
    node_code VARCHAR(64) NOT NULL,
    network_id BIGINT NULL,
    node_type VARCHAR(32) NULL,
    node_name VARCHAR(128) NULL,
    longitude DECIMAL(12,7) NULL,
    latitude DECIMAL(12,7) NULL,
    elevation_m DECIMAL(10,2) NULL,
    access_status TINYINT NULL,
    online_flag TINYINT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_asset_node_code (node_code),
    KEY idx_asset_node_network_id (network_id),
    KEY idx_asset_node_type (node_type),
    KEY idx_asset_node_name (node_name),
    KEY idx_asset_node_longitude (longitude),
    KEY idx_asset_node_latitude (latitude),
    KEY idx_asset_node_online_flag (online_flag),
    KEY idx_asset_node_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS asset_facility (
    id BIGINT NOT NULL,
    facility_code VARCHAR(64) NOT NULL,
    section_id BIGINT NULL,
    node_id BIGINT NULL,
    facility_type VARCHAR(32) NULL,
    facility_name VARCHAR(128) NULL,
    manufacturer VARCHAR(128) NULL,
    install_date DATE NULL,
    maintain_cycle_day INT NULL,
    facility_status TINYINT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_asset_facility_code (facility_code),
    KEY idx_asset_facility_section_id (section_id),
    KEY idx_asset_facility_node_id (node_id),
    KEY idx_asset_facility_type (facility_type),
    KEY idx_asset_facility_name (facility_name),
    KEY idx_asset_facility_status (facility_status),
    KEY idx_asset_facility_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =========================
-- 设备测点域
-- =========================
CREATE TABLE IF NOT EXISTS iot_device (
    id BIGINT NOT NULL,
    device_code VARCHAR(64) NOT NULL,
    device_name VARCHAR(128) NULL,
    device_type VARCHAR(32) NULL,
    protocol_type VARCHAR(32) NULL,
    gateway_code VARCHAR(64) NULL,
    facility_id BIGINT NULL,
    region_code VARCHAR(32) NULL,
    online_status TINYINT NULL,
    last_online_time DATETIME NULL,
    firmware_version VARCHAR(64) NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_device_code (device_code),
    KEY idx_iot_device_name (device_name),
    KEY idx_iot_device_type (device_type),
    KEY idx_iot_device_gateway_code (gateway_code),
    KEY idx_iot_device_facility_id (facility_id),
    KEY idx_iot_device_region_code (region_code),
    KEY idx_iot_device_online_status (online_status),
    KEY idx_iot_device_last_online_time (last_online_time),
    KEY idx_iot_device_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS iot_measure_point (
    id BIGINT NOT NULL,
    point_code VARCHAR(64) NOT NULL,
    point_name VARCHAR(128) NULL,
    device_id BIGINT NOT NULL,
    section_id BIGINT NULL,
    node_id BIGINT NULL,
    metric_type VARCHAR(32) NOT NULL,
    unit_name VARCHAR(16) NULL,
    sample_cycle_sec INT NULL,
    threshold_min DECIMAL(16,4) NULL,
    threshold_max DECIMAL(16,4) NULL,
    point_status TINYINT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_measure_point_code (point_code),
    KEY idx_iot_measure_point_name (point_name),
    KEY idx_iot_measure_point_device_id (device_id),
    KEY idx_iot_measure_point_section_id (section_id),
    KEY idx_iot_measure_point_node_id (node_id),
    KEY idx_iot_measure_point_metric_type (metric_type),
    KEY idx_iot_measure_point_status (point_status),
    KEY idx_iot_measure_point_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =========================
-- 时序域
-- =========================
CREATE TABLE IF NOT EXISTS ts_measure_current (
    id BIGINT NOT NULL,
    point_id BIGINT NOT NULL,
    metric_type VARCHAR(32) NULL,
    current_value DECIMAL(18,6) NOT NULL,
    quality_flag TINYINT NULL,
    alarm_flag TINYINT NULL,
    collect_time DATETIME NOT NULL,
    receive_time DATETIME NULL,
    edge_node_code VARCHAR(64) NULL,
    raw_payload JSON NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ts_measure_current_point_id (point_id),
    KEY idx_ts_measure_current_metric_type (metric_type),
    KEY idx_ts_measure_current_quality_flag (quality_flag),
    KEY idx_ts_measure_current_alarm_flag (alarm_flag),
    KEY idx_ts_measure_current_collect_time (collect_time),
    KEY idx_ts_measure_current_receive_time (receive_time),
    KEY idx_ts_measure_current_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ts_measure_history (
    id BIGINT NOT NULL,
    point_id BIGINT NOT NULL,
    section_id BIGINT NULL,
    metric_type VARCHAR(32) NULL,
    metric_value DECIMAL(18,6) NOT NULL,
    quality_flag TINYINT NULL,
    collect_time TIMESTAMP NOT NULL,
    receive_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    calc_tag VARCHAR(32) NULL,
    trace_id VARCHAR(64) NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_ts_measure_history_point_collect (point_id, collect_time DESC),
    KEY idx_ts_measure_history_section_collect (section_id, collect_time DESC),
    KEY idx_ts_measure_history_metric_type (metric_type),
    KEY idx_ts_measure_history_quality_flag (quality_flag),
    KEY idx_ts_measure_history_trace_id (trace_id),
    KEY idx_ts_measure_history_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- =========================
-- 告警工单域
-- =========================
CREATE TABLE IF NOT EXISTS ops_alert_rule (
    id BIGINT NOT NULL,
    rule_code VARCHAR(64) NOT NULL,
    rule_name VARCHAR(128) NOT NULL,
    metric_type VARCHAR(32) NULL,
    target_scope VARCHAR(255) NULL,
    rule_expr VARCHAR(1000) NOT NULL,
    alert_level TINYINT NULL,
    merge_window_min INT NULL,
    notify_channel VARCHAR(255) NULL,
    rule_status TINYINT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ops_alert_rule_code (rule_code),
    KEY idx_ops_alert_rule_metric_type (metric_type),
    KEY idx_ops_alert_rule_alert_level (alert_level),
    KEY idx_ops_alert_rule_rule_status (rule_status),
    KEY idx_ops_alert_rule_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ops_alert_event (
    id BIGINT NOT NULL,
    alert_code VARCHAR(64) NOT NULL,
    rule_id BIGINT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    point_id BIGINT NULL,
    alert_title VARCHAR(255) NOT NULL,
    alert_level TINYINT NULL,
    alert_status TINYINT NULL,
    occur_time DATETIME NOT NULL,
    confirm_time DATETIME NULL,
    close_time DATETIME NULL,
    work_order_id BIGINT NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ops_alert_event_code (alert_code),
    KEY idx_ops_alert_event_rule_id (rule_id),
    KEY idx_ops_alert_event_target (target_type, target_id),
    KEY idx_ops_alert_event_point_id (point_id),
    KEY idx_ops_alert_event_level (alert_level),
    KEY idx_ops_alert_event_status (alert_status),
    KEY idx_ops_alert_event_occur_time (occur_time),
    KEY idx_ops_alert_event_work_order_id (work_order_id),
    KEY idx_ops_alert_event_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ops_work_order (
    id BIGINT NOT NULL,
    work_order_code VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NULL,
    source_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    target_type VARCHAR(32) NULL,
    target_id BIGINT NULL,
    region_code VARCHAR(32) NULL,
    assignee_user_id BIGINT NULL,
    work_status TINYINT NULL,
    expect_finish_time DATETIME NULL,
    actual_finish_time DATETIME NULL,
    result_summary VARCHAR(500) NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ops_work_order_code (work_order_code),
    KEY idx_ops_work_order_source (source_type, source_id),
    KEY idx_ops_work_order_target (target_type, target_id),
    KEY idx_ops_work_order_region_code (region_code),
    KEY idx_ops_work_order_assignee (assignee_user_id),
    KEY idx_ops_work_order_status (work_status),
    KEY idx_ops_work_order_expect_finish_time (expect_finish_time),
    KEY idx_ops_work_order_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ops_work_order_log (
    id BIGINT NOT NULL,
    work_order_id BIGINT NOT NULL,
    action_type VARCHAR(32) NULL,
    operator_user_id BIGINT NULL,
    action_time DATETIME NOT NULL,
    before_status TINYINT NULL,
    after_status TINYINT NULL,
    action_desc VARCHAR(500) NULL,
    attachment_group_id BIGINT NULL,
    location_text VARCHAR(255) NULL,
    created_by BIGINT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_ops_work_order_log_work_order (work_order_id),
    KEY idx_ops_work_order_log_action_type (action_type),
    KEY idx_ops_work_order_log_operator (operator_user_id),
    KEY idx_ops_work_order_log_action_time (action_time),
    KEY idx_ops_work_order_log_after_status (after_status),
    KEY idx_ops_work_order_log_work_order_action_time (work_order_id, action_time DESC),
    KEY idx_ops_work_order_log_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
